version: 2
jobs:
  checkout:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: ls -al workspace
      - run: bash $PWD/scripts/checkout.sh /tmp/workspace $PWD/standaardenregister.json
      - run:
          name: List the files which have been created
          command: ls -al /tmp/workspace/*
      - run:
          name: List all standards that have been modified
          command: if [ -e /tmp/workspace/changedstandards.json ] ; then cat /tmp/workspace/changedstandards.json ; fi
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - changedstandards.json
            - commit.json
            - tmp-register.txt
            - repositories/
  extract-descriptions:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: bash $PWD/scripts/extract-descriptions.sh /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - description-paths.txt
  markdown-to-html:
    docker:
      - image: ddvlanck/markdown-to-html:1.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: bash $PWD/scripts/markdown-transformer.sh /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - descriptions/          -
workflows:
  version: 2
  create_detail_page:
    jobs:
      - checkout
      - extract-descriptions:
          requires:
            - checkout
